dist: xenial
sudo: false
language: python
cache: pip
python: 3.7
before_script: "pip install -r requirements.txt"
script:
  - "coverage run --source=messagemaker -m unittest -v"
  - "coverage report --show-missing"
after_success:
  - "sudo apt-get install sox zip"
  - "cd audio"
  - "mkdir package"
  - "ls *wav | xargs -L 1 -I {} sox --norm {}  -b 16 -c 1 -r 7350 package/{}"
  - "ls *wav | sed 's/.wav//g' | xargs -L 1 -I {} echo 'RECORD:{}:{}.wav' > package/atisfiles.txt"
  - "zip -r ../package.zip package/"
  - "cd .."
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "package.zip"
  skip_cleanup: true
  on:
    tags: true
